apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-react-app
spec:
  type: {{ .Values.client.type }}
  selector:
    app: {{ .Release.Name }}-react-app
  ports:
    - port: {{ .Values.client.port }}
      targetPort: {{ .Values.client.port }}